server = "xxx"

##################################################
## black list
##################################################
[[process]]
policy = "black"
Field = "Cmd"
matchType = "contain"
matchContent = "curl"

[[process]]
policy = "black"
Field = "Cmd"
matchType = "contain"
matchContent = "wget"

[[process]]
policy = "black"
Field = "Cmd"
matchType = "contain"
matchContent = "chmod"

[[process]]
policy = "black"
Field = "Cmd"
matchType = "contain"
matchContent = "ipset"

[[process]]
policy = "black"
Field = "Cmd"
matchType = "contain"
matchContent = "c.pyc"


##################################################
## white list
##################################################

[[process]]
policy = "white"
Field = "Name"
matchType = "regex"
matchContent = "^(nice|man-db.cron|ionice|id|systemd-tmpfiles|locale|anacron|systemd-tmpfile|pickup|free|tr|seq|mdatp|dmidecode|sh|mount|journalctl|sestatus|getenforce|ss|ip6tables|stat|aide|sendmail|rm|unix_chkpwd|cut|mkdir|xtrabackup|which|perl|du|xargs|systemd-cgroups|grepconf.sh|touch|mandb|renice|gzip|logrotate|0anacron|sa2|sa1|dpkg|run-parts|bash|rmdir|sh|lsof|sar|awk|diff|jcmd|sleep|top|clear|consoletype|SenseImdsCollector|df|rpm|last|sort|logger|basename|systemd-cgroups-agent|sadc|cat|who|id|hostname|uname|ps|tail|ls|pkg-config|grep|date|whoami|sed|who|wc|osqueryi|netstat|ip|tput|dircolors)\\b.*" # wazuh
#setsid|git|vte-urlencode-c|jspawnhelper|
[[process]]
policy = "white"
Field = "Cmd"
matchType = "equal"
matchContent = "-bash" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "equal"
matchContent = "/usr/bin/tty -s" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "equal"
matchContent = "/usr/sbin/unix_chkpwd root chkexpiry" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "equal"
matchContent = "sh -c [ -d /var/log/packages ] && echo true" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "contain"
matchContent = "/opt/webapps/gameplat" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "start"
matchContent = "find /var/log/sa" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "contain"
matchContent = "microsoft/mdatp" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "equal"
matchContent = "rm -f /var/lock/man-db.lock" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "start"
matchContent = "find /opt/lucky/db_xtrabackup/log" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "start"
matchContent = "/usr/bin/find /opt/lucky/db_xtrabackup/full" # open bash


[[process]]
policy = "white"
Field = "Cmd"
matchType = "start"
matchContent = "/usr/sbin/sshd -D -R" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "equal"
matchContent = "useradd -D" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "equal"
matchContent = "sshd -T" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "start"
matchContent = "find /etc/ssh -xdev" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "start"
matchContent = "systemctl status" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "start"
matchContent = "systemctl is-enabled" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "start"
matchContent = "find /var/log" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "start"
matchContent = "iptables -L" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "start"
matchContent = "ip6tables -L" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "equal"
matchContent = "/usr/bin/python2 -Es /usr/bin/firewall-cmd --state" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "start"
matchContent = "modprobe -n -v" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "equal"
matchContent = "/sbin/modprobe -q --" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "equal"
matchContent = "/sbin/modprobe -q -- netdev-" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "start"
matchContent = "sysctl net.ipv4" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "start"
matchContent = "sysctl net.ipv6" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "start"
matchContent = "/usr/bin/python /usr/bin/yum check-update" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "equal"
matchContent = "sysctl kernel.randomize_va_space" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "equal"
matchContent = "sysctl fs.suid_dumpable" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "equal"
matchContent = "crontab -u root -l" # open bash

[[process]]
policy = "white"
Field = "Cmd"
matchType = "start"
matchContent = "/opt/lucky/apps/mysql/bin/mysql -uzabbixmonitor"

[[process]]
policy = "white"
Field = "Cmd"
matchType = "equal"
matchContent = "/opt/lucky/jdk/bin/java --version"

[[process]]
policy = "white"
Field = "Cmd"
matchType = "equal"
matchContent = "/usr/bin/python /usr/libexec/urlgrabber-ext-down"

[[process]]
policy = "white"
Field = "Cmd"
matchType = "contain"
matchContent = "AnsiballZ_ping.py"

[[process]]
policy = "white"
Field = "Cmd"
matchType = "start"
matchContent = "/usr/sbin/ipset list"

[[process]]
policy = "white"
Field = "Cmd"
matchType = "equal"
matchContent = "/usr/bin/python2 -Es /bin/firewall-cmd --reload"

[[process]]
policy = "white"
Field = "Cmd"
matchType = "equal"
matchContent = "/usr/bin/python2 -Es /bin/firewall-cmd --list-all"

[[process]]
policy = "white"
Field = "Cmd"
matchType = "equal"
matchContent = "/usr/sbin/ipset restore"

[[process]]
policy = "white"
Field = "Cmd"
matchType = "equal"
matchContent = "/usr/sbin/iptables-restore -w -n"

[[process]]
policy = "white"
Field = "Cmd"
matchType = "equal"
matchContent = "/usr/sbin/ebtables-restore --noflush"

[[process]]
policy = "white"
Field = "Cmd"
matchType = "regex"
matchContent = "^/usr/sbin/ipset destroy .*whitelist$"

[[process]]
policy = "white"
Field = "Cmd"
matchType = "equal"
matchContent = "/usr/sbin/modprobe nf_conntrack"

[[process]]
policy = "white"
Field = "Cmd"
matchType = "equal"
matchContent = "ipset --help"

[[process]]
policy = "white"
Field = "Cmd"
matchType = "equal"
matchContent = "iptables -w10 -p icmp --help"